In [ ]:
import os
import numpy as np
import pandas as pd
import mne
import mne_bids
from pathlib import Path

# -----------------------------
# Dataset information
# -----------------------------
bids_dir = r"E:\IEEG-FMRI Dataset"

subjects = mne_bids.get_entity_vals(bids_dir, "subject")

session = "iemu"
datatype = "ieeg"
task = "film"
acquisition = "clinical"

summary = []

# -----------------------------
# Loop through all subjects
# -----------------------------
for subject in subjects:

    print(f"\nProcessing subject {subject}")

    # Skip subjects without iEEG session
    iemu_folder = Path(bids_dir) / f"sub-{subject}" / "ses-iemu"

    if not iemu_folder.exists():
        print(f"Skipping subject {subject}: no iEEG session")
        continue

    # ------------------------------------
    # Read channels.tsv
    # ------------------------------------
    channels_path = mne_bids.BIDSPath(
        subject=subject,
        session=session,
        datatype=datatype,
        task=task,
        acquisition=acquisition,
        suffix="channels",
        extension=".tsv",
        root=bids_dir,
    )

    # print(subject)
    # print(channels_path)
    # print(channels_path.match())

    channels = pd.read_csv(channels_path.match()[0], sep="\t")

    # ------------------------------------
    # Read BrainVision recording
    # ------------------------------------
    data_path = mne_bids.BIDSPath(
        subject=subject,
        session=session,
        datatype=datatype,
        task=task,
        acquisition=acquisition,
        suffix="ieeg",
        extension=".vhdr",
        root=bids_dir,
    )

    raw = mne.io.read_raw_brainvision(
        str(data_path.match()[0]),
        preload=True,
        verbose=False,
    )

    # ------------------------------------
    # Keep only EEG / ECoG / SEEG channels
    # ------------------------------------
    raw.set_channel_types(
        {
            ch_name: str(ch_type).lower()
            if str(ch_type).lower() in ["ecog", "seeg", "eeg"]
            else "misc"
            for ch_name, ch_type in zip(
                raw.ch_names,
                channels["type"].values
            )
        }
    )

    raw.drop_channels(
        [
            ch
            for ch, typ in zip(raw.ch_names, raw.get_channel_types())
            if typ == "misc"
        ]
    )

    # ------------------------------------
    # Remove bad/noisy channels
    # ------------------------------------
    bad_channels = channels.loc[
        channels["status"] == "bad",
        "name"
    ].tolist()

    bad_channels = [ch for ch in bad_channels if ch in raw.ch_names]

    raw.drop_channels(bad_channels)

    # ------------------------------------
    # Remove 50 Hz line noise and its harmonics
    # ------------------------------------
    raw.notch_filter(freqs=np.arange(50, 251, 50))

    # ------------------------------------
    # Common Average Reference
    # ------------------------------------
    raw_car, _ = mne.set_eeg_reference(raw.copy(), "average")

    # Remove invalid measurement date
    raw_car.set_meas_date(None)

    save_dir = Path(r"E:\ieeg-fmri-dataset-analysis\preprocess")
    save_dir.mkdir(exist_ok=True)

    raw_car.save(
        save_dir / f"sub-{subject}_{task}_preprocessed_raw.fif",
        overwrite=True
    )

    # ------------------------------------
    # Store
    # ------------------------------------

    summary.append({
    "Subject": subject,
    "Sampling_Frequency": raw_car.info["sfreq"],
    "Channels_Remaining": len(raw_car.ch_names)
    })

    print(f"Sampling frequency: {raw_car.info['sfreq']} Hz")
    print(f"Remaining channels: {len(raw_car.ch_names)}")

summary_df = pd.DataFrame(summary)
summary_df

Processing subject 01

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, ORB+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.8s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    3.5s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-01_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-01_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 101

Processing subject 02

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:70: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-02_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-02_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 59

Processing subject 03
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8 has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-03_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-03_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 101

Processing subject 04
Skipping subject 04: no iEEG session

Processing subject 05

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG2, MKR1+, MKR2+, abdo+, emg1+, orb+, thor+, xxx1, xxx2, xxx3, xxx4, xxx5, xxx6, xxx7, xxx8 has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    2.6s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:   10.7s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-05_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-05_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 73

Processing subject 06

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, R1+, R2+, R3+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.7s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-06_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-06_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 102

Processing subject 07
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG4+, MKR+, abdo+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-07_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-07_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 55

Processing subject 08
Skipping subject 08: no iEEG session

Processing subject 09

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) EMG+, MKR1+, MKR2+, ORB+, ah+, ecg+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.9s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-09_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-09_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 69

Processing subject 10

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-10_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-10_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 90

Processing subject 11
Skipping subject 11: no iEEG session

Processing subject 12

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.8s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-12_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-12_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 64

Processing subject 13

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG1, ECG2, MKR1+, MKR2+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-13_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-13_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 94

Processing subject 14

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) EMG1+, EMG2+, R1, R1+, R2, R2+, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-14_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-14_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 109

Processing subject 15
Skipping subject 15: no iEEG session

Processing subject 16

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, emg1+, emg2+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-16_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-16_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 103

Processing subject 17

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-17_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-17_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 89

Processing subject 18

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, R2+, R3+, R4+, R5+, orb+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-18_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-18_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 61

Processing subject 19

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.7s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-19_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-19_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 78

Processing subject 20

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-20_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-20_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 88

Processing subject 21

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) Ah1+, MKR1+, MKR2+, Orb1+, ecg2+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.9s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    8.1s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-21_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-21_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 109

Processing subject 22

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-22_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-22_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 51

Processing subject 23

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.5s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    6.9s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:   15.9s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-23_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-23_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 164

Processing subject 24

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, emg1+, emg2+, orb+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-24_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-24_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 71

Processing subject 25

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:70: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-25_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-25_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 60

Processing subject 26

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.8s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-26_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-26_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 81

Processing subject 27

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-27_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-27_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 91

Processing subject 28

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:70: RuntimeWarning: Limited 2 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-28_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-28_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 83

Processing subject 29
Skipping subject 29: no iEEG session

Processing subject 30

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-30_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-30_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 56

Processing subject 31

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-31_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-31_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 96

Processing subject 32

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-32_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-32_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 43

Processing subject 33
Filtering raw data in 1 contiguous segment

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, orb+ has changed from V to NA.
  raw.set_channel_types(

Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.5s

Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-33_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-33_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 72

Processing subject 34

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG2, MKR1+, MKR2+, abdo+, emg1+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.7s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-34_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-34_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 95

Processing subject 35
Skipping subject 35: no iEEG session

Processing subject 36

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg1+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.6s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    6.7s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-36_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-36_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 72

Processing subject 37
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-37_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-37_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 78

Processing subject 38
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, EMG2, Orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-38_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-38_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 101

Processing subject 39
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:70: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s

Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-39_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-39_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 80

Processing subject 40
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:70: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, emg+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-40_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-40_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 69

Processing subject 41
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, R1, R2, R3, R4, R5, R6, R7, R8 has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.4s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-41_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-41_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 79

Processing subject 42

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) MKR1+, MKR2+, ah1+, ecg1+, emg1+, orb1+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.6s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    2.7s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-42_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-42_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 105

Processing subject 43
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, EMG1+, EMG2+, R1+, R2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-43_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-43_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 116

Processing subject 44
Skipping subject 44: no iEEG session

Processing subject 45
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, R1+, R2+, abdo+, emg+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-45_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-45_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 77

Processing subject 46
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg+, emg2+, emg3+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-46_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-46_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 59

Processing subject 47
Skipping subject 47: no iEEG session

Processing subject 48
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, emg1+, emg2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-48_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-48_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 83

Processing subject 49
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-49_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-49_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 107

Processing subject 50
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, Orb+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-50_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-50_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 69

Processing subject 51

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) MKR1+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-51_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-51_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 69

Processing subject 52
Skipping subject 52: no iEEG session

Processing subject 53
Skipping subject 53: no iEEG session

Processing subject 54
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) emg, orb has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-54_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-54_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 64

Processing subject 55
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, R1, R1+, R2, R2+, R3, R3+, R4, R4+, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-55_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-55_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 94

Processing subject 56
Skipping subject 56: no iEEG session

Processing subject 57
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-57_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-57_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 61

Processing subject 58
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.5s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-58_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-58_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 104

Processing subject 59
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, ORB+, abdo+, emg1+, emg2+, emg3+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-59_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-59_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 60

Processing subject 60
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) ECG+, R1+, emg1+, emg2+, emg3+, emg4+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-60_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-60_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 107

Processing subject 61

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, abdo+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.7s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-61_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-61_film_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 58

Processing subject 62
Skipping subject 62: no iEEG session

Processing subject 63
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1217013557.py:79: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, Orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-63_film_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-63_film_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 70

   Subject  Sampling_Frequency  Channels_Remaining
0       01              2048.0                 101
1       02               512.0                  59
2       03               512.0                 101
3       05              2048.0                  73
4       06               512.0                 102
5       07               512.0                  55
6       09              2048.0                  69
7       10               512.0                  90
8       12              2048.0                  64
9       13               512.0                  94
10      14               512.0                 109
11      16               512.0                 103
12      17               512.0                  89
13      18               512.0                  61
14      19               512.0                  78
15      20               512.0                  88
16      21              2048.0                 109
17      22               512.0                  51
18      23              2048.0                 164
19      24               512.0                  71
20      25              2048.0                  60
21      26               512.0                  81
22      27               512.0                  91
23      28               512.0                  83
24      30              2048.0                  56
25      31               512.0                  96
26      32              2048.0                  43
27      33               512.0                  72
28      34               512.0                  95
29      36              2048.0                  72
30      37               512.0                  78
31      38               512.0                 101
32      39               512.0                  80
33      40               512.0                  69
34      41               512.0                  79
35      42              2048.0                 105
36      43               512.0                 116
37      45               512.0                  77
38      46               512.0                  59
39      48               512.0                  83
40      49               512.0                 107
41      50               512.0                  69
42      51              2048.0                  69
43      54               512.0                  64
44      55               512.0                  94
45      57               512.0                  61
46      58               512.0                 104
47      59               512.0                  60
48      60               512.0                 107
49      61              2048.0                  58
50      63               512.0                  70

In [ ]:
# #PREPROCESSING FOR REST FILES

# import os
# import numpy as np
# import pandas as pd
# import mne
# import mne_bids
# from pathlib import Path

# # -----------------------------
# # Dataset information
# # -----------------------------
# bids_dir = r"E:\IEEG-FMRI Dataset"

# subjects = mne_bids.get_entity_vals(bids_dir, "subject")

# session = "iemu"
# datatype = "ieeg"
# task = "rest"
# acquisition = "clinical"

# summary = []

# # -----------------------------
# # Loop through all subjects
# # -----------------------------
# for subject in subjects:

#     print(f"\nProcessing subject {subject}")

#     # Skip subjects without iEEG session
#     iemu_folder = Path(bids_dir) / f"sub-{subject}" / "ses-iemu"

#     if not iemu_folder.exists():
#         print(f"Skipping subject {subject}: no iEEG session")
#         continue

#     # ------------------------------------
#     # Read channels.tsv
#     # ------------------------------------
#     channels_path = mne_bids.BIDSPath(
#         subject=subject,
#         session=session,
#         datatype=datatype,
#         task=task,
#         acquisition=acquisition,
#         suffix="channels",
#         extension=".tsv",
#         root=bids_dir,
#     )

#     print(subject)
#     print(channels_path)
#     print(channels_path.match())


#     channels = pd.read_csv(channels_path.match()[0], sep="\t")

#     # ------------------------------------
#     # Read BrainVision recording
#     # ------------------------------------
#     data_path = mne_bids.BIDSPath(
#         subject=subject,
#         session=session,
#         datatype=datatype,
#         task=task,
#         acquisition=acquisition,
#         suffix="ieeg",
#         extension=".vhdr",
#         root=bids_dir,
#     )

#     raw = mne.io.read_raw_brainvision(
#         str(data_path.match()[0]),
#         preload=True,
#         verbose=False,
#     )

#     # ------------------------------------
#     # Keep only EEG / ECoG / SEEG channels
#     # ------------------------------------
#     raw.set_channel_types(
#         {
#             ch_name: str(ch_type).lower()
#             if str(ch_type).lower() in ["ecog", "seeg", "eeg"]
#             else "misc"
#             for ch_name, ch_type in zip(
#                 raw.ch_names,
#                 channels["type"].values
#             )
#         }
#     )

#     raw.drop_channels(
#         [
#             ch
#             for ch, typ in zip(raw.ch_names, raw.get_channel_types())
#             if typ == "misc"
#         ]
#     )

#     # ------------------------------------
#     # Remove bad/noisy channels
#     # ------------------------------------
#     bad_channels = channels.loc[
#         channels["status"] == "bad",
#         "name"
#     ].tolist()

#     bad_channels = [ch for ch in bad_channels if ch in raw.ch_names]

#     raw.drop_channels(bad_channels)

#     # ------------------------------------
#     # Remove 50 Hz line noise and its harmonics
#     # ------------------------------------
#     raw.notch_filter(freqs=np.arange(50, 251, 50))

#     # ------------------------------------
#     # Common Average Reference
#     # ------------------------------------
#     raw_car, _ = mne.set_eeg_reference(raw.copy(), "average")

#     # Remove invalid measurement date
#     raw_car.set_meas_date(None)

#     save_dir = Path(r"E:\ieeg-fmri-dataset-analysis\preprocess")
#     save_dir.mkdir(exist_ok=True)

#     raw_car.save(
#         save_dir / f"sub-{subject}_{task}_preprocessed_raw.fif",
#         overwrite=True
#     )

#     # ------------------------------------
#     # Store
#     # ------------------------------------

#     summary.append({
#     "Subject": subject,
#     "Sampling_Frequency": raw_car.info["sfreq"],
#     "Channels_Remaining": len(raw_car.ch_names)
#     })

#     print(f"Sampling frequency: {raw_car.info['sfreq']} Hz")
#     print(f"Remaining channels: {len(raw_car.ch_names)}")

# summary_df = pd.DataFrame(summary)
# summary_df

#SUB-33 DOESN'T HAVE A REST FILE. AND THE ABOVE CODE STOPS AT SUB-33. SO WE FIX THE ISSUE

Processing subject 01
01
E:/IEEG-FMRI Dataset/sub-01/ses-iemu/ieeg/sub-01_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-01_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, ORB+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-01_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-01_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 102

Processing subject 02
02
E:/IEEG-FMRI Dataset/sub-02/ses-iemu/ieeg/sub-02_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-02_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-02_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-02_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 60

Processing subject 03
03
E:/IEEG-FMRI Dataset/sub-03/ses-iemu/ieeg/sub-03_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-03_ses-iemu_task-rest_acq-clinical_run-4_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8 has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.1s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-03_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-03_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 101

Processing subject 04
Skipping subject 04: no iEEG session

Processing subject 05
05
E:/IEEG-FMRI Dataset/sub-05/ses-iemu/ieeg/sub-05_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-05_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG2, MKR1+, MKR2+, abdo+, emg1+, thor+ has changed from V to NA.
  raw.set_channel_types(

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s

Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-05_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-05_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 75

Processing subject 06
06
E:/IEEG-FMRI Dataset/sub-06/ses-iemu/ieeg/sub-06_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-06_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, R1+, R2+, R3+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.3s

Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-06_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-06_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 101

Processing subject 07
07
E:/IEEG-FMRI Dataset/sub-07/ses-iemu/ieeg/sub-07_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-07_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, EMG4+, MKR+, abdo+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-07_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-07_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 55

Processing subject 08
Skipping subject 08: no iEEG session

Processing subject 09
09
E:/IEEG-FMRI Dataset/sub-09/ses-iemu/ieeg/sub-09_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-09_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) EMG+, MKR1+, MKR2+, ORB+, ah+, ecg+ has changed from V to NA.
  raw.set_channel_types(

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-09_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-09_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 69

Processing subject 10
10
E:/IEEG-FMRI Dataset/sub-10/ses-iemu/ieeg/sub-10_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-10_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.1s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-10_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-10_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 90

Processing subject 11
Skipping subject 11: no iEEG session

Processing subject 12
12
E:/IEEG-FMRI Dataset/sub-12/ses-iemu/ieeg/sub-12_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-12_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-12_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-12_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 64

Processing subject 13
13
E:/IEEG-FMRI Dataset/sub-13/ses-iemu/ieeg/sub-13_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-13_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG1, ECG2, MKR1+, MKR2+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-13_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-13_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 94

Processing subject 14
14
E:/IEEG-FMRI Dataset/sub-14/ses-iemu/ieeg/sub-14_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-14_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) EMG1+, EMG2+, R1, R1+, R2, R2+, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-14_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-14_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 109

Processing subject 15
Skipping subject 15: no iEEG session

Processing subject 16
16
E:/IEEG-FMRI Dataset/sub-16/ses-iemu/ieeg/sub-16_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-16_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, emg1+, emg2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-16_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-16_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 103

Processing subject 17
17
E:/IEEG-FMRI Dataset/sub-17/ses-iemu/ieeg/sub-17_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-17_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-17_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-17_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 89

Processing subject 18
18
E:/IEEG-FMRI Dataset/sub-18/ses-iemu/ieeg/sub-18_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-18_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) EMG+, MKR1+, MKR2+, R2+, R3+, R4+, R5+ has changed from V to NA.
  raw.set_channel_types(

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-18_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-18_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 60

Processing subject 19
19
E:/IEEG-FMRI Dataset/sub-19/ses-iemu/ieeg/sub-19_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-19_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-19_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-19_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 78

Processing subject 20
20
E:/IEEG-FMRI Dataset/sub-20/ses-iemu/ieeg/sub-20_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-20_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-20_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-20_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 88

Processing subject 21
21
E:/IEEG-FMRI Dataset/sub-21/ses-iemu/ieeg/sub-21_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-21_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) Ah1+, MKR1+, MKR2+, Orb1+, ecg2+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.9s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-21_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-21_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 109

Processing subject 22
22
E:/IEEG-FMRI Dataset/sub-22/ses-iemu/ieeg/sub-22_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-22_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-22_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-22_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 51

Processing subject 23
23
E:/IEEG-FMRI Dataset/sub-23/ses-iemu/ieeg/sub-23_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-23_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:    3.1s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-23_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-23_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 164

Processing subject 24
24
E:/IEEG-FMRI Dataset/sub-24/ses-iemu/ieeg/sub-24_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-24_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, emg1+, emg2+, orb+ has changed from V to NA.
  raw.set_channel_types(

- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-24_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-24_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 72

Processing subject 25
25
E:/IEEG-FMRI Dataset/sub-25/ses-iemu/ieeg/sub-25_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-25_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.8s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-25_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-25_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 60

Processing subject 26
26
E:/IEEG-FMRI Dataset/sub-26/ses-iemu/ieeg/sub-26_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-26_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.7s

Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-26_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-26_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 81

Processing subject 27
27
E:/IEEG-FMRI Dataset/sub-27/ses-iemu/ieeg/sub-27_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-27_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-27_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-27_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 91

Processing subject 28
28
E:/IEEG-FMRI Dataset/sub-28/ses-iemu/ieeg/sub-28_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-28_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s

Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-28_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-28_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 82

Processing subject 29
Skipping subject 29: no iEEG session

Processing subject 30
30
E:/IEEG-FMRI Dataset/sub-30/ses-iemu/ieeg/sub-30_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-30_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) ECG+, MKR+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.8s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-30_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-30_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 56

Processing subject 31
31
E:/IEEG-FMRI Dataset/sub-31/ses-iemu/ieeg/sub-31_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-31_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:73: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-31_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-31_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 96

Processing subject 32
32
E:/IEEG-FMRI Dataset/sub-32/ses-iemu/ieeg/sub-32_ses-iemu_task-rest_acq-clinical_channels.tsv
[BIDSPath(
root: E:/IEEG-FMRI Dataset
datatype: ieeg
basename: sub-32_ses-iemu_task-rest_acq-clinical_run-1_channels.tsv)]
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\3641657625.py:82: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-32_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-32_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 43

Processing subject 33
33
E:/IEEG-FMRI Dataset/sub-33/ses-iemu/ieeg/sub-33_ses-iemu_task-rest_acq-clinical_channels.tsv
[]

IndexError: list index out of range

In [4]:
#PREPROCESSING FOR REST FILES

import os
import numpy as np
import pandas as pd
import mne
import mne_bids
from pathlib import Path

# -----------------------------
# Dataset information
# -----------------------------
bids_dir = r"E:\IEEG-FMRI Dataset"

subjects = mne_bids.get_entity_vals(bids_dir, "subject")

session = "iemu"
datatype = "ieeg"
task = "rest"
acquisition = "clinical"

summary = []

# -----------------------------
# Loop through all subjects
# -----------------------------
for subject in subjects:

    print(f"\nProcessing subject {subject}")

    # Skip subjects without iEEG session
    iemu_folder = Path(bids_dir) / f"sub-{subject}" / "ses-iemu"

    if not iemu_folder.exists():
        print(f"Skipping subject {subject}: no iEEG session")
        continue

    # ------------------------------------
    # Read channels.tsv
    # ------------------------------------
    ieeg_dir = Path(bids_dir) / f"sub-{subject}" / f"ses-{session}" / datatype

    channel_files = sorted(
        ieeg_dir.glob(f"*task-{task}_acq-clinical*_channels.tsv")
    )

    if len(channel_files) == 0:
        print(f"No channels file found for subject {subject}")
        continue

    channels = pd.read_csv(channel_files[0], sep="\t")

    # ------------------------------------
    # Read BrainVision recording
    # ------------------------------------
    vhdr_files = sorted(
    ieeg_dir.glob(f"*task-{task}_acq-clinical*_ieeg.vhdr")
)

    if len(vhdr_files) == 0:
        print(f"No recording found for subject {subject}")
        continue

    raw = mne.io.read_raw_brainvision(
        str(vhdr_files[0]),
        preload=True,
        verbose=False,
    )

    # ------------------------------------
    # Keep only EEG / ECoG / SEEG channels
    # ------------------------------------
    raw.set_channel_types(
        {
            ch_name: str(ch_type).lower()
            if str(ch_type).lower() in ["ecog", "seeg", "eeg"]
            else "misc"
            for ch_name, ch_type in zip(
                raw.ch_names,
                channels["type"].values
            )
        }
    )

    raw.drop_channels(
        [
            ch
            for ch, typ in zip(raw.ch_names, raw.get_channel_types())
            if typ == "misc"
        ]
    )

    # ------------------------------------
    # Remove bad/noisy channels
    # ------------------------------------
    bad_channels = channels.loc[
        channels["status"] == "bad",
        "name"
    ].tolist()

    bad_channels = [ch for ch in bad_channels if ch in raw.ch_names]

    raw.drop_channels(bad_channels)

    # ------------------------------------
    # Remove 50 Hz line noise and its harmonics
    # ------------------------------------
    raw.notch_filter(freqs=np.arange(50, 251, 50))

    # ------------------------------------
    # Common Average Reference
    # ------------------------------------
    raw_car, _ = mne.set_eeg_reference(raw.copy(), "average")

    # Remove invalid measurement date
    raw_car.set_meas_date(None)

    save_dir = Path(r"E:\ieeg-fmri-dataset-analysis\preprocess")
    save_dir.mkdir(exist_ok=True)

    raw_car.save(
        save_dir / f"sub-{subject}_{task}_preprocessed_raw.fif",
        overwrite=True
    )

    # ------------------------------------
    # Store
    # ------------------------------------

    summary.append({
    "Subject": subject,
    "Sampling_Frequency": raw_car.info["sfreq"],
    "Channels_Remaining": len(raw_car.ch_names)
    })

    print(f"Sampling frequency: {raw_car.info['sfreq']} Hz")
    print(f"Remaining channels: {len(raw_car.ch_names)}")

summary_df = pd.DataFrame(summary)
summary_df

Processing subject 01

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, ORB+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-01_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-01_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 102

Processing subject 02

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-02_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-02_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 60

Processing subject 03

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8 has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.8s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-03_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-03_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 101

Processing subject 04
Skipping subject 04: no iEEG session

Processing subject 05

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG2, MKR1+, MKR2+, abdo+, emg1+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.9s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    4.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-05_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-05_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 75

Processing subject 06

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, R1+, R2+, R3+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.9s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-06_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-06_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 101

Processing subject 07
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, EMG4+, MKR+, abdo+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-07_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-07_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 55

Processing subject 08
Skipping subject 08: no iEEG session

Processing subject 09

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) EMG+, MKR1+, MKR2+, ORB+, ah+, ecg+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    1.1s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-09_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-09_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 69

Processing subject 10
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(

- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.9s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-10_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-10_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 90

Processing subject 11
Skipping subject 11: no iEEG session

Processing subject 12
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-12_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-12_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 64

Processing subject 13
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG1, ECG2, MKR1+, MKR2+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-13_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-13_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 94

Processing subject 14
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) EMG1+, EMG2+, R1, R1+, R2, R2+, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-14_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-14_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 109

Processing subject 15
Skipping subject 15: no iEEG session

Processing subject 16
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, emg1+, emg2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-16_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-16_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 103

Processing subject 17
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-17_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-17_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 89

Processing subject 18
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) EMG+, MKR1+, MKR2+, R2+, R3+, R4+, R5+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-18_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-18_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 60

Processing subject 19
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-19_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-19_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 78

Processing subject 20
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG1+, EMG2+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-20_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-20_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 88

Processing subject 21

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) Ah1+, MKR1+, MKR2+, Orb1+, ecg2+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.5s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-21_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-21_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 109

Processing subject 22
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-22_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-22_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 51

Processing subject 23

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s
[Parallel(n_jobs=1)]: Done 161 tasks      | elapsed:    3.1s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-23_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-23_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 164

Processing subject 24
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, emg1+, emg2+, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-24_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-24_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 72

Processing subject 25
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-25_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-25_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 60

Processing subject 26
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-26_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-26_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 81

Processing subject 27
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-27_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-27_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 91

Processing subject 28
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, ORB+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-28_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-28_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 82

Processing subject 29
Skipping subject 29: no iEEG session

Processing subject 30
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-30_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-30_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 56

Processing subject 31
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, R1, R2, R3, R4, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-31_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-31_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 96

Processing subject 32
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Overwriting existing file.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-32_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-32_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 43

Processing subject 33
No channels file found for subject 33

Processing subject 34

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG2, MKR1+, MKR2+, abdo+, emg1+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.3s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-34_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-34_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 95

Processing subject 35
Skipping subject 35: no iEEG session

Processing subject 36
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg1+, thor+ has changed from V to NA.
  raw.set_channel_types(

---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.2s

Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-36_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-36_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 72

Processing subject 37
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, EMG+, MKR1+, MKR2+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.3s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-37_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-37_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 82

Processing subject 38
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, Orb+, abdo+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-38_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-38_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 97

Processing subject 39
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.4s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-39_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-39_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 80

Processing subject 40
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-40_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-40_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 69

Processing subject 41
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, R1, R2, R3, R4, R5, R6, R7, R8 has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.3s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-41_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-41_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 79

Processing subject 42

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) MKR1+, MKR2+, ah1+, ecg1+, emg1+, orb1+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.4s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.6s

sEEG channel type selected for re-referencing
Applying average reference.
Applying a custom ('sEEG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-42_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-42_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 108

Processing subject 43
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, EMG1+, EMG2+, R1+, R2+ has changed from V to NA.
  raw.set_channel_types(

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.8s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-43_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-43_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 116

Processing subject 44
Skipping subject 44: no iEEG session

Processing subject 45

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, R1+, R2+, abdo+, emg+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.7s

Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-45_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-45_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 73

Processing subject 46
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg+, emg2+, emg3+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-46_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-46_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 59

Processing subject 47
Skipping subject 47: no iEEG session

Processing subject 48
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, emg1+, emg2+, orb+ has changed from V to NA.
  raw.set_channel_types(

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.3s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    1.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-48_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-48_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 82

Processing subject 49
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.6s

Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-49_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-49_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 107

Processing subject 50
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, Orb+, abdo+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-50_rest_preprocessed_raw.fif

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-50_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 71

Processing subject 51
Filtering raw data in 1 contiguous segment

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) MKR1+ has changed from V to NA.
  raw.set_channel_types(

Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-51_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-51_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 69

Processing subject 52
Skipping subject 52: no iEEG session

Processing subject 53
Skipping subject 53: no iEEG session

Processing subject 54
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, MKR1+, MKR2+, abdo+, emg+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-54_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-54_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 65

Processing subject 55
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, R1, R1+, R2, R2+, R3, R3+, R4, R4+, R5, R6, R7, R8, orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing
Applying average reference.

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.3s

Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-55_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-55_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 94

Processing subject 56
Skipping subject 56: no iEEG session

Processing subject 57

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.8s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-57_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-57_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 61

Processing subject 58

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, abdo+, emg1+, emg2+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(

Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.9s
[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    3.7s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-58_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-58_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 104

Processing subject 59
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, MKR1+, MKR2+, ORB+, abdo+, emg1+, emg2+, emg3+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-59_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-59_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 60

Processing subject 60
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:64: RuntimeWarning: Limited 1 annotation(s) that were expanding outside the data range.
  raw = mne.io.read_raw_brainvision(
C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) ECG+, R1+, emg1+, emg2+, emg3+, emg4+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.0s

ECoG channel type selected for re-referencing

[Parallel(n_jobs=1)]: Done  71 tasks      | elapsed:    0.2s

Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-60_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-60_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 107

Processing subject 61
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 13517 samples (6.600 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, abdo+, orb+, thor+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.2s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-61_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-61_rest_preprocessed_raw.fif
[done]
Sampling frequency: 2048.0 Hz
Remaining channels: 58

Processing subject 62
Skipping subject 62: no iEEG session

Processing subject 63
Filtering raw data in 1 contiguous segment
Setting up band-stop filter

FIR filter parameters
---------------------
Designing a one-pass, zero-phase, non-causal bandstop filter:
- Windowed time-domain design (firwin) method
- Hamming window with 0.0194 passband ripple and 53 dB stopband attenuation
- Lower transition bandwidth: 0.50 Hz
- Upper transition bandwidth: 0.50 Hz
- Filter length: 3381 samples (6.604 s)

C:\Users\muqadasah\AppData\Local\Temp\ipykernel_17888\1264894985.py:73: RuntimeWarning: The unit for channel(s) AH+, ECG+, EMG+, MKR1+, MKR2+, Orb+ has changed from V to NA.
  raw.set_channel_types(
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s

ECoG channel type selected for re-referencing
Applying average reference.
Applying a custom ('ECoG',) reference.
Writing E:\ieeg-fmri-dataset-analysis\preprocess\sub-63_rest_preprocessed_raw.fif
Closing E:\ieeg-fmri-dataset-analysis\preprocess\sub-63_rest_preprocessed_raw.fif
[done]
Sampling frequency: 512.0 Hz
Remaining channels: 70

   Subject  Sampling_Frequency  Channels_Remaining
0       01              2048.0                 102
1       02              2048.0                  60
2       03               512.0                 101
3       05              2048.0                  75
4       06               512.0                 101
5       07               512.0                  55
6       09              2048.0                  69
7       10               512.0                  90
8       12              2048.0                  64
9       13               512.0                  94
10      14               512.0                 109
11      16               512.0                 103
12      17               512.0                  89
13      18               512.0                  60
14      19               512.0                  78
15      20               512.0                  88
16      21              2048.0                 109
17      22               512.0                  51
18      23              2048.0                 164
19      24               512.0                  72
20      25              2048.0                  60
21      26               512.0                  81
22      27               512.0                  91
23      28               512.0                  82
24      30              2048.0                  56
25      31               512.0                  96
26      32              2048.0                  43
27      34              2048.0                  95
28      36              2048.0                  72
29      37               512.0                  82
30      38               512.0                  97
31      39              2048.0                  80
32      40               512.0                  69
33      41               512.0                  79
34      42              2048.0                 108
35      43               512.0                 116
36      45               512.0                  73
37      46               512.0                  59
38      48               512.0                  82
39      49               512.0                 107
40      50               512.0                  71
41      51              2048.0                  69
42      54               512.0                  65
43      55               512.0                  94
44      57              2048.0                  61
45      58              2048.0                 104
46      59              2048.0                  60
47      60               512.0                 107
48      61              2048.0                  58
49      63               512.0                  70